### ISSUE TITLE
Incorrect Red Highlighting Of Some Patterns

### ISSUE THREAD

**Issue by markcf** [textmate/toml.tmbundle#8]
Hello,

If you look at Toml's official spec:
https://github.com/toml-lang/toml

There are some problems with the things being highlighted in red. One example is under the heading "Key/Value Pair".

![image](https://cloud.githubusercontent.com/assets/4062180/13866551/f3774f58-ec8c-11e5-9a51-5ac1042873d3.png)

**Comment by infininight** [comment]
Thanks, this fix has been deployed for TextMate users. For the Github parser it will be pulled in the next update of the various grammars which typically happens every 4-6 weeks.
